// Emoji到uView图标的映射表
const emojiMap = {
  // 常用图标
  '🏠': 'home',
  '👤': 'account',
  '👥': 'account',
  '📋': 'list',
  '📅': 'calendar',
  '🔍': 'search',
  '📊': 'chart-line',
  '⚙️': 'setting',
  '🔔': 'bell',
  '📱': 'phone',
  '📝': 'edit-pen',
  '✅': 'checkmark-circle',
  '❌': 'close-circle',
  '⏳': 'clock',
  '📄': 'file-text',
  '📸': 'camera',
  '🛍️': 'shopping-cart',
  '🎁': 'gift',
  '⭐': 'star',
  '🏆': 'trophy',
  '📍': 'map-pin',
  '🕐': 'clock',
  '💰': 'rmb-circle',
  '📦': 'bag',
  '✏️': 'edit-pen',
  '🗑️': 'trash',
  '➕': 'plus-circle',
  '➖': 'minus-circle',
  '🔒': 'lock',
  '🔓': 'unlock',
  '👁️': 'eye',
  '💬': 'chat',
  '📧': 'email',
  '🌟': 'star-fill',
  '❤️': 'heart-fill',
  '📌': 'pushpin',
  '🔗': 'link',
  '📂': 'folder',
  '🖼️': 'photo',
  '🎯': 'aim',
  '🔥': 'fire',
  '⚡': 'flash',
  '🎨': 'palette',
  '🎵': 'music',
  '🎮': 'game',
  '🏅': 'medal',
  '📈': 'trending-up',
  '📉': 'trending-down',
  '🔄': 'reload',
  '⬆️': 'arrow-up',
  '⬇️': 'arrow-down',
  '⬅️': 'arrow-left',
  '➡️': 'arrow-right',
  '✔️': 'checkmark',
  '⚠️': 'warning',
  '❗': 'info-circle',
  '❓': 'question-circle'
}

console.log('Emoji映射表：')
console.log(JSON.stringify(emojiMap, null, 2))
